# Change baseurl before deploy
baseurl = "https://blog.8688886.xyz"
languageCode = "en-ZH"
title = "八  六"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5



[params]
  description = "------*------"
  # author = "八六"
  [params.author]
    name = "八 六"
    email = "86@example.com"

